<html>
 <head>
  <title>Chrissyx Webring und Toplist</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <meta name="dc.language" scheme="rfc1766" content="de">
  <meta name="robots" content="index, follow">
  <meta name="revisit-after" content="7 days">
  <meta name="description" content="Toplist und Webring and much more...">
  <meta name="author" content="Chrissyx">
  <meta name="Copyright" content="Chrissyx">
  <meta name="keywords" content="chrissyx, toplist, webring, erben">
  <link rel="SHORTCUT ICON" href="http://www.chrissyx.com/favicon.ico">
  <link rel="stylesheet" type="text/css" href="style.css">
 </head>

 <body>
  <center>

  <table width="700">

   <tr>
    <td colspan="3"><a href="liste.php"><img src="top.jpg" border="0" alt="Chrissyx Toplist und Webring"></a></td>
   </tr>
   <tr>
    <td valign="top" background="left.jpg"><img src="left.jpg"></td>
    <td><center>